language: ruby

before_install: gem install bundler

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.4
  - 2.5.3

matrix:
  include:
    - rvm: 2.4
      gemfile: gemfiles/mime_types_1.gemfile
    - rvm: 2.4
      gemfile: gemfiles/mime_types_2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/mime_types_3.gemfile

deploy:
  provider: rubygems
  api_key:
    secure: BMsVwSCrMbeCVICWMe5dobyr5nMOcugTwlDOjZCuWprIH/nk1G9zlRDO+j86/FGsc9yDolv4QM8HmS4KwA+/kiWfRRJtXsD9VEUkSwaSji8rFKpBaZjm9cZ13LNX5/LOzWW/n3nXGfbkNlpmIbX9XQt3BG7fVL5EVj03k7EQe4w=
  gem: swagger-core
  on:
    tags: true
    repo: swagger-rb/swagger-rb
